os: linux
language: node_js
node_js:
  - "stable"

notifications:
  email: false

cache:
  directories:
    - node_modules

# Specify which branches to build using a safelist, or blocklist branches that you do not want to be built:
branches:
  only:
    - master
    - develop

script:
  - npm test
  - npm run build

deploy:
  - provider: pages

    # Set in the settings page of your repository, as a secure variable
    token: $GITHUB_TOKEN

    on:
      branch: master

    # Make sure you have skip_cleanup set to true, otherwise Travis CI will delete all the files created during the
    # build, which will probably delete what you are trying to upload.
    skip_cleanup: true

    # Directory to push to GitHub Pages, defaults to current directory. Can be specified as an absolute path or a
    # relative path from the current directory.
    local_dir: build

    # Repo slug, defaults to current repo. Note: The slug consists of username and repo name and is formatted like
    # user/repo-name.
    repo: D3strukt0r/weleda-webcenter-text-export-prod

    # Branch to (force, see: keep_history) push local_dir contents to, defaults to gh-pages.
    target_branch: master

    # Optional, sets a custom domain for your website, defaults to no custom domain support.
    fqdn: webcenter-text-export.manuele-vaccari.ch

  - provider: pages
    token: $GITHUB_TOKEN
    on:
      branch: develop
    skip_cleanup: true
    local_dir: build
    repo: D3strukt0r/weleda-webcenter-text-export-dev
    target_branch: master
    fqdn: webcenter-text-export-dev.manuele-vaccari.ch

