version: "3.4"

services:
  client:
    build:
      context: .
      target: development
    tty: true # https://github.com/facebook/create-react-app/issues/8688
    ports:
      - 80:3000
    volumes:
      - .:/app:rw,cached
