blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/D3strukt0r/weleda-webcenter-text-export/discussions
    about: Please ask and answer questions here.
