name: CI/CD

on:
  push:
    branches:
      - master
      - develop
    paths:
      - .github/workflows/ci-cd.yml
      # - "docker/**"
      - "public/**"
      - "src/**"
      # - .dockerignore
      - .yarnrc.yml
      # - docker-compose.build.yml
      # - Dockerfile
      - package.json
      - tsconfig.json
      - yarn.lock

  pull_request:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      # https://github.com/actions/cache/blob/main/examples.md#node---yarn-2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests
        run: yarn run test

      - name: Build
        run: yarn run build

  publish:
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.repository == 'D3strukt0r/weleda-webcenter-text-export'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Setup Travis DPL
        run: |
          sudo apt update
          sudo apt install -y ruby
          sudo gem install dpl --pre

      # https://github.com/actions/cache/blob/main/examples.md#node---yarn-2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn run build

      # https://github.com/travis-ci/dpl#github-pages
      - name: Deploy to Github Pages (Production)
        if: github.ref == 'refs/heads/master'
        run: |
          dpl pages git \
              --repo D3strukt0r/weleda-webcenter-text-export-prod \
              --token ${{ secrets.PAT }} \
              --target_branch master \
              --keep_history \
              --allow_empty_commit \
              --verbose \
              --local_dir build \
              --fqdn webcenter-text-export.manuele-vaccari.ch

      - name: Deploy to Github Pages (Development)
        if: github.ref == 'refs/heads/develop'
        run: |
          dpl pages git \
              --repo D3strukt0r/weleda-webcenter-text-export-dev \
              --token ${{ secrets.PAT }} \
              --target_branch master \
              --keep_history \
              --allow_empty_commit \
              --verbose \
              --local_dir build \
              --fqdn webcenter-text-export-dev.manuele-vaccari.ch
