name: CI/CD

on:
  push:
    branches:
      - master
      - develop

  # Run tests for any PRs.
  pull_request:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm 
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build
      
      - name: Run tests
        run: yarn test

  publish:
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
        
      - name: Setup Travis DPL
        run: |
          sudo apt update
          sudo apt install -y ruby
          sudo gem install dpl --pre

      - name: Setup Git
        run: |
          git config --global user.name "Github Action"
          git config --global user.email "action@github.com"
      
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm 
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: yarn --frozen-lockfile
      
      - name: Build
        run: yarn build
      
      # https://github.com/travis-ci/dpl#github-pages
      - name: Deploy to Github Pages (Production)
        if: github.ref == 'refs/heads/master'
        run: |
          dpl pages git \
              --repo D3strukt0r/weleda-webcenter-text-export-prod \
              --token ${{ secret.GITHUB_TOKEN }} \
              --target_branch master \
              --keep_history \
              --allow_empty_commit \
              --verbose \
              --local_dir build \
              --fqdn webcenter-text-export.manuele-vaccari.ch
      - name: Deploy to Github Pages (Development)
        if: github.ref == 'refs/heads/develop'
        run: |
          dpl pages git \
              --repo D3strukt0r/weleda-webcenter-text-export-dev \
              --token ${{ secret.GITHUB_TOKEN }} \
              --target_branch master \
              --keep_history \
              --allow_empty_commit \
              --verbose \
              --local_dir build \
              --fqdn webcenter-text-export-dev.manuele-vaccari.ch
