name: CI/CD

on:
  push:
    branches:
      - master
      - develop

  # Run tests for any PRs.
  pull_request:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      
      # https://github.com/actions/cache/blob/main/examples.md#node---yarn-2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache Node.js modules (Yarn v2)
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn run build
      
      - name: Run tests
        run: yarn run test

  publish:
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
        
      - name: Setup Travis DPL
        run: |
          sudo apt update
          sudo apt install -y ruby
          sudo gem install dpl --pre

      - name: Setup Git
        run: |
          git config --global user.name "Github Action"
          git config --global user.email "action@github.com"

      # https://github.com/actions/cache/blob/main/examples.md#node---yarn-2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache Node.js modules (Yarn v2)
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --frozen-lockfile
      
      - name: Build
        run: yarn run build
      
      # https://github.com/travis-ci/dpl#github-pages
      - name: Deploy to Github Pages (Production)
        if: github.ref == 'refs/heads/master'
        run: |
          dpl pages git \
              --repo D3strukt0r/weleda-webcenter-text-export-prod \
              --token ${{ secrets.PAT }} \
              --target_branch master \
              --keep_history \
              --allow_empty_commit \
              --verbose \
              --local_dir build \
              --fqdn webcenter-text-export.manuele-vaccari.ch
      - name: Deploy to Github Pages (Development)
        if: github.ref == 'refs/heads/develop'
        run: |
          dpl pages git \
              --repo D3strukt0r/weleda-webcenter-text-export-dev \
              --token ${{ secrets.PAT }} \
              --target_branch master \
              --keep_history \
              --allow_empty_commit \
              --verbose \
              --local_dir build \
              --fqdn webcenter-text-export-dev.manuele-vaccari.ch
