name: Update Docker Hub Description

on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml

  workflow_dispatch: ~

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: echo "::set-output name=repository::$(echo "${{ secrets.DOCKER_IMAGE }}" | tr '[A-Z]' '[a-z]')"

      - uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ steps.prep.outputs.repository }}
          short-description: ${{ github.event.repository.description }}
